// 门店管理
export const MERCHANT_LIST_SUC = 'MERCHANT_LIST_SUC'
export const MERCHANT_INFO_SUC = 'MERCHANT_INFO_SUC'
export const MERCHANT_ADD_LOADING = 'MERCHANT_ADD_LOADING'
export const MERCHANT_REMOVE_LOADING = 'MERCHANT_REMOVE_LOADING'

// 订单管理
export const ORDER_LIST_SUC = 'ORDER_LIST_SUC'
export const ORDER_ADD_LOADING = 'ORDER_ADD_LOADING'
export const ORDER_REMOVE_LOADING = 'ORDER_REMOVE_LOADING'

// 商品分类管理
export const CATEGROY_LIST_SUC = 'CATEGROY_LIST_SUC'
export const CATEGORY_INFO_SUC = 'CATEGORY_INFO_SUC'
export const GOODS_CATEGORY_SUC = 'GOODS_CATEGORY_SUC'
export const CATEGROY_ADD_LOADING = 'CATEGROY_ADD_LOADING'
export const CATEGROY_REMOVE_LOADING = 'CATEGROY_REMOVE_LOADING'

// 单品管理
export const GOODS_LIST_SUC = 'GOODS_LIST_SUC'
export const GOODS_INFO_SUC = 'GOODS_INFO_SUC'
export const GOODS_ADD_LOADING = 'GOODS_ADD_LOADING'
export const GOODS_REMOVE_LOADING = 'GOODS_REMOVE_LOADING'

// 统计管理
export const STAT_LIST_SUC = 'STAT_LIST_SUC'
